### ISSUE TITLE
Country Code block no longer working

### ISSUE THREAD

**Issue by poprz** [W1zzardTPU/XenForo_TPUDetectSpamReg#3]
The country code always returns XX.  This may be because http://api.hostip.info is always down or has a bad dns entry. I don't know how long it's been down for, but at least a few weeks continuously. This is going to prevent all country code lookups from working. 

FYI: This prevents the following sample country lookup from working :http://api.hostip.info/country.php?ip=184.71.55.21

**Comment by Xon** [comment]
https://freegeoip.net/ runs a free geoip service (upto 10,000 queries per hour. not an issue for XenForo signups), and can be configured to run as a standalone service. I've used this elsewhere and it works reasonably well.

Based of the Maxmind heoip database (free), but supports being configured to automatically update from a paid-for version given credentials.

Github profile: https://github.com/fiorix/freegeoip

**Comment by poprz** [comment]
Great idea, but this doesn't appear to work.  I tried the edits submitted yet it is still reporting as "Country Detected: XX"

**Comment by centminmod** [comment]
maybe add a 3rd provider https://xenforo.com/community/threads/tpu-detect-and-block-spam-registrations.70418/page-12#post-1056400

```
curl http://ipinfo.io/8.8.8.8
{
  "ip": "8.8.8.8",
  "hostname": "google-public-dns-a.google.com",
  "city": "Mountain View",
  "region": "California",
  "country": "US",
  "loc": "37.3845,-122.0881",
  "org": "AS15169 Google Inc.",
  "postal": "94040"
}
```

**Comment by Xon** [comment]
Fyi, #5 will address easily changing IP country APIs. However UI work is still to be done.
